### ISSUE TITLE
Implement `vm.stopBroadcast()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#144]
#### 📝 Description

Implementing the `vm.stopBroadcast()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/stop-broadcast.md).

**Declaration**
```solidity
function stopBroadcast() external;
```

#### 🤔 Rationale

This method is required to stop collecting transactions for later on-chain broadcasting.

#### 🖼️ Mockups/Examples

```solidity
function deployNoArgs() public {
    // broadcast the next call
    cheats.broadcast();
    Test test1 = new Test();

    // broadcast all calls between this line and `stopBroadcast`
    cheats.startBroadcast();
    Test test2 = new Test();
    cheats.stopBroadcast();
}
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.stopBroadcast()` should take no arguments
    - Returns no value

2. **Unit Tests:**
    - Write unit tests ensuring `stopBroadcast()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `stopBroadcast()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.stopBroadcast()`
- [ ] Write tests for `stopBroadcast()`
- [ ] Add inline documentation for `stopBroadcast()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
