### ISSUE TITLE
Implement `vm.startBroadcast()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#145]
#### 📝 Description

Implementing the `vm.startBroadcast()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/start-broadcast.md).

**Declaration**
```solidity
function startBroadcast() external;
function startBroadcast(address who) external;
function startBroadcast(uint256 privateKey) external;
```

#### 🤔 Rationale

This method is required to have all subsequent calls (at this call depth only and excluding cheatcode calls) create transactions that can later be signed and sent onchain using the address that calls the test contract or the address / private key provided as the sender.

#### 🖼️ Mockups/Examples

```solidity
function t(uint256 a) public returns (uint256) {
    uint256 b = 0;
    emit log_string("here");
    return b;
}

function deployOther() public {
    vm.startBroadcast(ACCOUNT_A);
    Test test = new Test();
    
    // will trigger a transaction
    test.t(1);
    
    vm.stopBroadcast();

    // broadcast again, this time using a private key from your environment variables
    vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
    test.t(3);
    vm.stopBroadcast();
}
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.startBroadcast()` should take either `address` or `uint256`
    - Returns no value

2. **Unit Tests:**
    - Write unit tests ensuring `startBroadcast()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `startBroadcast()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.startBroadcast()`
- [ ] Write tests for `startBroadcast()`
- [ ] Add inline documentation for `startBroadcast()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
