### ISSUE TITLE
Implement `vm.tryFfi()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#146]
#### 📝 Description

Implementing the `vm.tryFfi()` cheat code.

**Declaration**
```solidity
function tryFfi(string commands) external returns (Vm.FfiResult);
```

#### 🤔 Rationale

This method is required to run an `ffi` command surrounded by a `try`-`catch`.

#### 🖼️ Mockups/Examples

```solidity
  function ipfsHashFile(Vm vm, string memory filePath, bool upload) internal returns (bytes32) {
    string[] memory inputs = new string[](7);
    inputs[0] = 'npx';
    inputs[1] = '--yes';
    inputs[2] = '-s';
    inputs[3] = '@bgd-labs/aave-cli@0.0.24-34c06df8b6ba4225f0828e126ea62096c8e57d9f.0';
    inputs[4] = 'ipfs';
    inputs[5] = filePath;
    if (upload) {
      inputs[6] = '-u';
    }
    Vm.FfiResult memory f = vm.tryFfi(inputs);
    if (f.exitCode != 0) {
      console2.logString(string(f.stderr));
      revert FfiFailed();
    }
    require(f.stdout.length != 0, 'CALCULATED_HASH_IS_ZERO');
    console2.logString('Info: This preview will only work when the file has been uploaded to ipfs');
    console2.logString(
      string(
        abi.encodePacked(
          'Preview: https://app.aave.com/governance/ipfs-preview/?ipfsHash=',
          vm.toString(f.stdout)
        )
      )
    );
    return bytes32(f.stdout);
  }
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.tryFfi()` should take `string`
    - Returns `FfiResult` 

2. **Unit Tests:**
    - Write unit tests ensuring `tryFfi()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `tryFfi()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.tryFfi()`
- [ ] Write tests for `tryFfi()`
- [ ] Add inline documentation for `tryFfi()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
