### ISSUE TITLE
Implement `vm.ffi()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#147]
#### 📝 Description

Implementing the `vm.ffi()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/ffi.md).

**Declaration**
```solidity
function ffi(string[] calldata) external returns (bytes memory);
```

#### 🤔 Rationale

This method is required to call an arbitrary command if [`ffi`](https://github.com/foundry-rs/book/blob/master/src/reference/config/testing.md#ffi) is enabled.

#### 🖼️ Mockups/Examples

ABI encoded output

```solidity
string[] memory inputs = new string[](3);
inputs[0] = "echo";
inputs[1] = "-n";
// ABI encoded "gm", as a hex string
inputs[2] = "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002676d000000000000000000000000000000000000000000000000000000000000";

bytes memory res = vm.ffi(inputs);
string memory output = abi.decode(res, (string));
assertEq(output, "gm");
```

UTF8 string output

```solidity
string[] memory inputs = new string[](3);
inputs[0] = "echo";
inputs[1] = "-n";
inputs[2] = "gm";

bytes memory res = vm.ffi(inputs);
assertEq(string(res), "gm");
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.ffi()` should take an array of `string`
    - Returns `bytes` 

2. **Unit Tests:**
    - Write unit tests ensuring `ffi()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `ffi()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.ffi()`
- [ ] Write tests for `ffi()`
- [ ] Add inline documentation for `ffi()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
