### ISSUE TITLE
Implement `vm.load()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#148]
#### 📝 Description

Implementing the `vm.load()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/load.md).

**Declaration**
```solidity
function load(address account, bytes32 slot) external returns (bytes32);
```

#### 🤔 Rationale

This method is required to load the value from storage slot `slot` on account `account`.

#### 🖼️ Mockups/Examples

```solidity
/// contract LeetContract {
///     uint256 private leet = 1337; // slot 0
/// }

bytes32 leet = vm.load(address(leetContract), bytes32(uint256(0)));
emit log_uint(uint256(leet)); // 1337
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.load()` should take `address` and `bytes32`
    - Returns `bytes32` 

2. **Unit Tests:**
    - Write unit tests ensuring `load()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `load()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.load()`
- [ ] Write tests for `load()`
- [ ] Add inline documentation for `load()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
