### ISSUE TITLE
Implement `vm.store()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#149]
#### 📝 Description

Implementing the `vm.store()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/store.md).

**Declaration**
```solidity
function store(address account, bytes32 slot, bytes32 value) external;
```

#### 🤔 Rationale

This method is required to store the value `value` in storage slot `slot` on account `account`.

#### 🖼️ Mockups/Examples

```solidity
/// contract LeetContract {
///     uint256 private leet = 1337; // slot 0
/// }

vm.store(address(leetContract), bytes32(uint256(0)), bytes32(uint256(31337)));
bytes32 leet = vm.load(address(leetContract), bytes32(uint256(0)));
emit log_uint(uint256(leet)); // 31337
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.store()` should take `account`, `bytes32` and `bytes32`
    - Returns no value

2. **Unit Tests:**
    - Write unit tests ensuring `store()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `store()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.store()`
- [ ] Write tests for `store()`
- [ ] Add inline documentation for `store()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
