### ISSUE TITLE
Implement `vm.serializeBool()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#150]
#### 📝 Description

Implementing the `vm.serializeBool()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/serialize-json.md).

**Declaration**
```solidity
function serializeBool(string calldata objectKey, string calldata valueKey, bool value) external returns (string memory json);
```

#### 🤔 Rationale

This method is required to serialize `bool` type as a stringified JSON object.

#### 🖼️ Mockups/Examples

```solidity
string memory obj1 = "some key";
vm.serializeBool(obj1, "boolean", true);
vm.serializeUint(obj1, "number", uint256(342));
string memory obj2 = "some address key";
string memory output = vm.serializeAddress(obj2, "string", msg.sender);
string memory finalJson = vm.serializeString(obj1, "object", output);

vm.writeJson(finalJson, "./output/example.json");
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.serializeBool()` should take `string`, `string` and `bool`
    - Returns a `string` 

2. **Unit Tests:**
    - Write unit tests ensuring `serializeBool()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `serializeBool()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.serializeBool()`
- [ ] Write tests for `serializeBool()`
- [ ] Add inline documentation for `serializeBool()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
