### ISSUE TITLE
Implement `vm.serializeUint()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#152]
#### 📝 Description

Implementing the `vm.serializeUint()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/serialize-json.md).

**Declaration**
```solidity
function serializeUint(string calldata objectKey, string calldata valueKey, uint256[] calldata values) external returns (string memory json);
```

#### 🤔 Rationale

This method is required to serialize uint values as a stringified JSON object.

#### 🖼️ Mockups/Examples

```solidity
string memory obj1 = "some key";
vm.serializeBool(obj1, "boolean", true);
vm.serializeUint(obj1, "number", uint256(342));

string memory obj2 = "some other key";
string memory output = vm.serializeString(obj2, "title", "finally json serialization");

// IMPORTANT: This works because `serializeString` first tries to interpret `output` as
//   a stringified JSON object. If the parsing fails, then it treats it as a normal
//   string instead.
//   For instance, an `output` equal to '{ "ok": "asd" }' will produce an object, but
//   an output equal to '"ok": "asd" }' will just produce a normal string.
string memory finalJson = vm.serializeString(obj1, "object", output);

vm.writeJson(finalJson, "./output/example.json");
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.serializeUint()` should take `string`, `string` and an unsigned integer type
    - Returns `string`

2. **Unit Tests:**
    - Write unit tests ensuring `serializeUint()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `serializeUint()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.serializeUint()`
- [ ] Write tests for `serializeUint()`
- [ ] Add inline documentation for `serializeUint()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
