### ISSUE TITLE
Implement `vm.isPersistent()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#153]
#### 📝 Description

Implementing the `vm.isPersistent()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/create-fork.md).

**Declaration**
```solidity
function isPersistent(address) external returns (bool);
```

#### 🤔 Rationale

This method is required to know whether an account is marked as persistent ([`makePersistent`](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/make-persistent.md)).

#### 🖼️ Mockups/Examples

```solidity
// By default the `sender` and the test contract itself are persistent
assert(cheats.isPersistent(msg.sender));
assert(cheats.isPersistent(address(this)));
```

#### 🖋️Requirements

1. **Implement the Method:**
    - `vm.isPersistent()` should take `address` as a parameter
    - Returns a `bool`

2. **Unit Tests:**
    - Write unit tests ensuring `isPersistent()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `isPersistent()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.isPersistent()`
- [ ] Write tests for `isPersistent()`
- [ ] Add inline documentation for `isPersistent()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
