### ISSUE TITLE
Implement `vm.revokePersistent()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#154]
#### 📝 Description

Implementing the `vm.revokePersistent()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/revoke-persistent.md).

**Declaration**
```solidity
function revokePersistent(address) external;
function revokePersistent(address[] calldata) external;
```

#### 🤔 Rationale

This method is required to make the given contract not persistent across fork swaps. Reverting [`makePersistent`](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/make-persistent.md).

#### 🖼️ Mockups/Examples

```solidity
contract SimpleStorageContract {
    string public value;

    function set(uint256 _value) public {
        value = _value;
    }
}

function testRevokePersistent() public {
    // select a specific fork
    cheats.selectFork(mainnetFork);
    
    // create a new contract that's stored in the `mainnetFork` storage
    SimpleStorageContract simple = new SimpleStorageContract();
    
    // `simple` is not marked as persistent
    assert(!cheats.isPersistent(address(simple)));
       
    // make it persistent
    cheats.makePersistent(address(simple));
    
    // ensure it is persistent
    assert(cheats.isPersistent(address(simple)));
    
    // revoke it
    cheats.revokePersistent(address(simple));
    
    // contract no longer persistent
    assert(!cheats.isPersistent(address(simple)));
}
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.revokePersistent()` should have two implementations:
      - the first takes `address`
      - the second takes an array of `address`
    - Returns no value

2. **Unit Tests:**
    - Write unit tests ensuring `revokePersistent()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `revokePersistent()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.revokePersistent()`
- [ ] Write tests for `revokePersistent()`
- [ ] Add inline documentation for `revokePersistent()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
