### ISSUE TITLE
Implement `vm.makePersistent()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#155]
#### 📝 Description

Implementing the `vm.makePersistent()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/make-persistent.md).

**Declaration**
```solidity
function makePersistent(address account) external;
function makePersistent(address account0, address account1) external;
function makePersistent(address account0, address account1, address account2) external;
function makePersistent(address[] calldata accounts) external;
```

#### 🤔 Rationale

This method is required to mark the specified accounts as persistent, which means that their state is available regardless of which fork is currently active.

> Each fork ([createFork](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/create-fork.md)) has its own independent storage, which is also replaced when another fork is selected ([selectFork](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/select-fork.md)). By default, only the test contract account and the caller are persistent across forks, which means that changes to the state of the test contract (variables) are preserved when different forks are selected. This way data can be shared by storing it in the contract's variables.

#### 🖼️ Mockups/Examples

```solidity
contract SimpleStorageContract {
    string public value;

    function set(uint256 _value) public {
        value = _value;
    }
}

function testMarkPersistent() public {
    // by default the `sender` and the contract itself are persistent
    assert(cheats.isPersistent(msg.sender));
    assert(cheats.isPersistent(address(this)));

    // select a specific fork
    cheats.selectFork(mainnetFork);
    
    // create a new contract that's stored in the `mainnetFork` storage
    SimpleStorageContract simple = new SimpleStorageContract();
    
    // `simple` is not marked as persistent
    assert(!cheats.isPersistent(address(simple)));
    
    // contract can be used
    uint256 expectedValue = 99;
    simple.set(expectedValue);
    assertEq(simple.value(), expectedValue);
    
    // mark as persistent
    cheats.makePersistent(address(simple));
    
    // select a different fork
    cheats.selectFork(optimismFork);
    
    // ensure contract is still persistent   
    assert(cheats.isPersistent(address(simple)));
    
    // value is set as expected
    assertEq(simple.value(), expectedValue);
}
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.makePersistent()` should have four implementations:
      - the first takes `address`
      - the second takes `address` and `address`
      - the third takes `address` and `address` and `address`
      - the fourth takes an array of `address`
    - Returns no value

2. **Unit Tests:**
    - Write unit tests ensuring `makePersistent()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `makePersistent()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.makePersistent()`
- [ ] Write tests for `makePersistent()`
- [ ] Add inline documentation for `makePersistent()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
