### ISSUE TITLE
Implement `vm.transact()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#156]
#### 📝 Description

Implementing the `vm.transact()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/transact.md).

**Declaration**
```solidity
// Fetches the given transaction from the active fork and executes it on the current state
function transact(bytes32 txHash) external;
// Fetches the given transaction from the given fork and executes it on the current state
function transact(uint256 forkId, bytes32 txHash) external;
```

#### 🤔 Rationale

This method is required to fetch the Transaction from the provider and execute it on the current state in forking mode.

#### 🖼️ Mockups/Examples

```solidity
// Enter forking mode at block: https://etherscan.io/block/15596646
uint256 fork = vm.createFork(MAINNET_RPC_URL, 15596646);
vm.selectFork(fork);

// a random transfer transaction in the block: https://etherscan.io/tx/0xaba74f25a17cf0d95d1c6d0085d6c83fb8c5e773ffd2573b99a953256f989c89
bytes32 tx = 0xaba74f25a17cf0d95d1c6d0085d6c83fb8c5e773ffd2573b99a953256f989c89;

address sender = address(0xa98218cdc4f63aCe91ddDdd24F7A580FD383865b);
address recipient = address(0x0C124046Fa7202f98E4e251B50488e34416Fc306);

assertEq(sender.balance, 5764124000000000);
assertEq(recipient.balance, 3936000000000000);

// transfer amount: 0.003936 Ether
uint256 transferAmount = 3936000000000000;

// expected balance changes once the transaction is executed
uint256 expectedRecipientBalance = recipient.balance + transferAmount;
uint256 expectedSenderBalance = sender.balance - transferAmount;

// execute the transaction
vm.transact(tx);

// recipient received transfer
assertEq(recipient.balance, expectedRecipientBalance);

// sender's balance decreased by transferAmount and gas
assert(sender.balance < expectedSenderBalance);
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.transact()` should have two implementations:
      - the first takes `bytes32`
      - the second takes `uint256` and `bytes32`
    - Returns no value

2. **Unit Tests:**
    - Write unit tests ensuring `transact()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `transact()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.transact()`
- [ ] Write tests for `transact()`
- [ ] Add inline documentation for `transact()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!

**Comment by dutterbutter** [comment]
Implemented in https://github.com/matter-labs/foundry-zksync/pull/228
