### ISSUE TITLE
Implement `vm.rollFork()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#157]
#### 📝 Description

Implementing the `vm.rollFork()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/roll-fork.md).

**Declaration**
```solidity
// roll the _active_ fork to the given block
function rollFork(uint256 blockNumber) external;
```
```solidity
// roll the _active_ fork to the block in which the transaction was mined it and replays all previously executed transactions
function rollFork(bytes32 transaction) external;
```
```solidity
// Same as `rollFork(uint256 blockNumber)` but uses the fork corresponding to the `forkId`
function rollFork(uint256 forkId, uint256 blockNumber) external;
```
```solidity
// Same as `rollFork(bytes32 transaction)` but uses the fork corresponding to the `forkId`
function rollFork(uint256 forkId, bytes32 transaction) external;
```

#### 🤔 Rationale

This method is required to set `block.number`. If a fork identifier is passed as an argument, it will update that fork, otherwise it will update the currently active fork.

If a transaction hash is provided, it will roll the fork to the block the transaction was mined in and replays all previously executed transactions.

#### 🖼️ Mockups/Examples

Set `block.number` for the currently active fork:

```solidity
uint256 forkId = vm.createFork(MAINNET_RPC_URL);
vm.selectFork(forkId);

assertEq(block.number, 15_171_037); // as of time of writing, 2022-07-19 04:55:27 UTC

vm.rollFork(15_171_057);

assertEq(block.number, 15_171_057);
```

Set `block.number` for the fork identified by the passed `forkId` argument:

```solidity
uint256 optimismForkId = vm.createFork(OPTIMISM_RPC_URL);

vm.rollFork(optimismForkId, 1_337_000);

vm.selectFork(optimismForkId);

assertEq(block.number, 1_337_000);
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.rollFork()` should have four implementations:
      - the first takes `uint256`
      - the second takes `bytes32`
      - the third takes `uint256` and `uint256`
      - the fourth takes `uint256` and `bytes32`
    - Returns no value

2. **Unit Tests:**
    - Write unit tests ensuring `rollFork()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `rollFork()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.rollFork()`
- [ ] Write tests for `rollFork()`
- [ ] Add inline documentation for `rollFork()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
