### ISSUE TITLE
Implement `vm.activeFork()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#158]
#### 📝 Description

Implementing the `vm.activeFork()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/active-fork.md).

**Declaration**
```solidity
function activeFork() external returns (uint256);
```

#### 🤔 Rationale

This method is required to return the identifier for the currently active fork. Reverts if no fork is currently active.

#### 🖼️ Mockups/Examples

```solidity
uint256 mainnetForkId = vm.createFork(MAINNET_RPC_URL);
uint256 optimismForkId = vm.createFork(OPTIMISM_RPC_URL);

assert(mainnetForkId != optimismForkId);

vm.selectFork(mainnetForkId);
assertEq(vm.activeFork(), mainnetForkId);

vm.selectFork(optimismForkId);
assertEq(vm.activeFork(), optimismForkId);
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.activeFork()` should take no parameters
    - Returns a `uint256` id value

2. **Unit Tests:**
    - Write unit tests ensuring `activeFork()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `activeFork()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.activeFork()`
- [ ] Write tests for `activeFork()`
- [ ] Add inline documentation for `activeFork()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
