### ISSUE TITLE
Implement `vm.rpcUrl()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#159]
#### 📝 Description

Implementing the `vm.rpcUrl()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/rpc.md).

**Declaration**
```solidity
// Returns the URL for a configured alias
function rpcUrl(string calldata alias) external returns(string memory);
```

#### 🤔 Rationale

This method is required to return the URL(s) for a configured alias(es).

#### 🖼️ Mockups/Examples

The following `rpc_endpoints` in `foundry.toml` registers two RPC aliases:

- `optimism` references the URL directly
- `mainnet` references the `RPC_MAINNET` environment value that is expected to contain the actual URL

*Env variables need to be wrapped in `${}`*

```toml
# --snip--
[rpc_endpoints]
optimism = "https://optimism.alchemyapi.io/v2/..."
mainnet = "${RPC_MAINNET}" 
```

```solidity
string memory url = vm.rpcUrl("optimism");
assertEq(url, "https://optimism.alchemyapi.io/v2/...");
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.rpcUrl()` should have two implementations:
      - the first takes `string`
      - the second, `vm.rpcUrls()` takes no parameters 
    - Returns a `string` value.
      - or an array of `string` pairs

2. **Unit Tests:**
    - Write unit tests ensuring `rpcUrl()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `rpcUrl()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.rpcUrl()`
- [ ] Implement `vm.rpcUrls()`
- [ ] Write tests for `rpcUrl()` and `rpcUrls()`
- [ ] Add inline documentation for `rpcUrl()` and `rpcUrls()`

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
