### ISSUE TITLE
Implement `vm.createSelectFork()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#160]
#### 📝 Description

Implementing the `vm.createSelectFork()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/create-select-fork.md).

**Declaration**
```solidity
function createSelectFork(string calldata urlOrAlias) external returns (uint256);
function createSelectFork(string calldata urlOrAlias, uint256 block) external returns (uint256);
function createSelectFork(string calldata urlOrAlias, bytes32 transaction) external returns (uint256);
```

#### 🤔 Rationale

This method is required to create _and_ select a new fork from the given endpoint and returns the identifier of the fork. If a block number is passed as an argument, the fork will begin on that block, otherwise it will begin on the _latest_ block.

If a transaction hash is provided, it will roll the fork to the block the transaction was mined in and replays all previously executed transactions.

#### 🖼️ Mockups/Examples

Create and select a new mainnet fork with the latest block number:

```solidity
uint256 forkId = vm.createSelectFork(MAINNET_RPC_URL);
assertEq(block.number, 15_171_037); // as of time of writing, 2022-07-19 04:55:27 UTC
```

Create and select a new mainnet fork with a given block number:

```solidity
uint256 forkId = vm.createSelectFork(MAINNET_RPC_URL, 1_337_000);
assertEq(block.number, 1_337_000);
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.createSelectFork()` should have three implementations:
      - the first takes `string`
      - the second takes `string` and `uint256`
      - the third takes `string` and `bytes32`
    - Returns a `uint256` fork id value.

2. **Unit Tests:**
    - Write unit tests ensuring `createSelectFork()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `createSelectFork()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.createSelectFork()`
- [ ] Write tests for `createSelectFork()`
- [ ] Add inline documentation for `createSelectFork()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
