### ISSUE TITLE
Implement `vm.selectFork()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#161]
#### 📝 Description

Implementing the `vm.selectFork()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/select-fork.md).

##### Declaration
```solidity
function selectFork(uint256 forkId) external;
```

#### 🤔 Rationale

This method is required to set the corresponding forked state as active by taking a fork identifier created by `createFork`.

#### 🖼️ Mockups/Examples

Select a previously created fork:

```solidity
uint256 forkId = vm.createFork(MAINNET_RPC_URL);

vm.selectFork(forkId);

assertEq(vm.activeFork(), forkId);
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.selectFork()` should take `uint256` as a parameter.
    - sets the corresponding forked state as active

2. **Unit Tests:**
    - Write unit tests ensuring `selectFork()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `selectFork()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.selectFork()`
- [ ] Write tests for `selectFork()`
- [ ] Add inline documentation for `selectFork()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
