### ISSUE TITLE
Implement `vm.createFork()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#162]
#### 📝 Description

Implementing the `vm.createFork()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/create-fork.md).

**Declaration**
```solidity
// Creates a new fork with the given endpoint and the _latest_ block and returns the identifier of the fork
function createFork(string calldata urlOrAlias) external returns (uint256)
// Creates a new fork with the given endpoint and block and returns the identifier of the fork
function createFork(string calldata urlOrAlias, uint256 block) external returns (uint256);
// Creates a new fork with the given endpoint and at the block the given transaction was mined in, 
// and replays all transaction mined in the block before the transaction
function createFork(string calldata urlOrAlias, bytes32 transaction) external returns (uint256);
```

#### 🤔 Rationale

This method is required to create a new fork from the given endpoint and returns the identifier of the fork. If a block number is passed as an argument, the fork will begin on that block, otherwise it will begin on the latest block.

If a transaction hash is provided, it will roll the fork to the block the transaction was mined in and replays all previously executed transactions.

#### 🖼️ Mockups/Examples

Create a new mainnet fork with the latest block number:

```solidity
uint256 forkId = vm.createFork(MAINNET_RPC_URL);
vm.selectFork(forkId);

assertEq(block.number, 15_171_037); // as of time of writing, 2022-07-19 04:55:27 UTC
```

Create a new mainnet fork with a given block number:

```solidity
uint256 forkId = vm.createFork(MAINNET_RPC_URL, 1_337_000);
vm.selectFork(forkId);

assertEq(block.number, 1_337_000);
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.createFork()` should have three implementations:
      - the first takes `string`
      - the second takes `string` and `uint256`
      - the third takes `string` and `bytes32`
    - Returns a `uint256` id value to select from later.

2. **Unit Tests:**
    - Write unit tests ensuring `createFork()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `createFork()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.createFork()`
- [ ] Write tests for `createFork()`
- [ ] Add inline documentation for `createFork()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
