### ISSUE TITLE
Implement `vm.writeFile()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#164]
#### 📝 Description

Implementing the `vm.writeFile()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/fs.md).

**Declaration**
```solidity
function writeFile(string calldata, string calldata) external;
```

#### 🤔 Rationale

This method is required to write data to a file, creating a file if it does not exist, and entirely replacing its contents if it does.

#### 🖼️ Mockups/Examples

**Requires read-write access to file / project root**

```solidity
string memory path = "file.txt";
string memory data = "hello world";
vm.writeFile(path, data);

assertEq(vm.readFile(path), data);
 ```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - `vm.writeFile()` should take in no parameters. 
    - Returns no values.

2. **Unit Tests:**
    - Write unit tests ensuring `writeFile()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `writeFile()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.writeFile()`
- [ ] Write tests for `writeFile()`
- [ ] Add inline documentation for `writeFile()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
