### ISSUE TITLE
Implement `vm.getRecordedLogs()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#168]
#### 📝 Description

Implementing the `vm.getRecordedLogs()` [cheat code](https://book.getfoundry.sh/cheatcodes/get-recorded-logs).

**Declaration**

```solidity
struct Log {
  bytes32[] topics;
  bytes data;
  address emitter;
}

function getRecordedLogs() external returns ( Log[] memory );
```

#### 🤔 Rationale

This method is required to get the emitted events recorded by `vm.recordLogs()`.

This function will consume the recorded logs when called.

#### 🖼️ Mockups/Examples

```solidity
/// event LogTopic1(
///   uint256 indexed topic1,
///   bytes data
/// );

/// event LogTopic12(
///   uint256 indexed topic1,
///   uint256 indexed topic2,
///   bytes data
/// );

/// bytes memory testData0 = "Some data";
/// bytes memory testData1 = "Other data";


// Start the recorder
vm.recordLogs();

emit LogTopic1(10, testData0);
emit LogTopic12(20, 30, testData1);

// Notice that your entries are <Interface>.Log[]
// as opposed to <instance>.Log[]
Vm.Log[] memory entries = vm.getRecordedLogs();

assertEq(entries.length, 2);

// Recall that topics[0] is the event signature
assertEq(entries[0].topics.length, 2);
assertEq(entries[0].topics[0], keccak256("LogTopic1(uint256,bytes)"));
assertEq(entries[0].topics[1], bytes32(uint256(10)));
// assertEq won't compare bytes variables. Try with strings instead.
assertEq(abi.decode(entries[0].data, (string)), string(testData0));

assertEq(entries[1].topics.length, 3);
assertEq(entries[1].topics[0], keccak256("LogTopic12(uint256,uint256,bytes)"));
assertEq(entries[1].topics[1], bytes32(uint256(20)));
assertEq(entries[1].topics[2], bytes32(uint256(30)));
assertEq(abi.decode(entries[1].data, (string)), string(testData1));

// Emit another event
emit LogTopic1(40, testData0);

// Your last read consumed the recorded logs,
// you will only get the latest emitted even after that call
entries = vm.getRecordedLogs();

assertEq(entries.length, 1);

assertEq(entries[0].topics.length, 2);
assertEq(entries[0].topics[0], keccak256("LogTopic1(uint256,bytes)"));
assertEq(entries[0].topics[1], bytes32(uint256(40)));
assertEq(abi.decode(entries[0].data, (string)), string(testData0));
 ```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should not take parameters.
    - It should return an array of `Log`.

2. **Unit Tests:**
    - Write unit tests ensuring `getRecordedLogs()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `getRecordedLogs()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.getRecordedLogs()`
- [ ] Write tests for `getRecordedLogs()`
- [ ] Add inline documentation for `getRecordedLogs()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
