### ISSUE TITLE
Implement `vm.recordLogs()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#169]
#### 📝 Description

Implementing the `vm.recordLogs()` [cheat code](https://book.getfoundry.sh/cheatcodes/record-logs).

**Declaration**
```solidity
function recordLogs() external;
```

#### 🤔 Rationale

This method is required start recording all the emitted events. Accessing these requires `vm.getRecordedLogs()`.

#### 🖼️ Mockups/Examples

```solidity
/// event LogCompleted(
///   uint256 indexed topic1,
///   bytes data
/// );

vm.recordLogs();

emit LogCompleted(10, "operation completed");

Vm.Log[] memory entries = vm.getRecordedLogs();

assertEq(entries.length, 1);
assertEq(entries[0].topics[0], keccak256("LogCompleted(uint256,bytes)"));
assertEq(entries[0].topics[1], bytes32(uint256(10)));
assertEq(abi.decode(entries[0].data, (string)), "operation completed");
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should not take parameters.
    - It should start recording emitted events after it has been called.

2. **Unit Tests:**
    - Write unit tests ensuring `recordLogs()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `recordLogs()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.recordLogs()`
- [ ] Write tests for `recordLogs()`
- [ ] Add inline documentation for `recordLogs()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
