### ISSUE TITLE
Implement `vm.expectRevert()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#170]
#### 📝 Description

Implementing the `vm.expectRevert()` [cheat code](https://book.getfoundry.sh/cheatcodes/expect-revert).

**Declaration**

Asserts that the next call reverts, regardless of the message:

```solidity
function expectRevert() external;
```
Asserts that the next call reverts with the specified 4 bytes:

```solidity
function expectRevert(bytes4 message) external;
```

Asserts that the next call reverts with the specified bytes:

```solidity
function expectRevert(bytes calldata message) external;
```

#### 🤔 Rationale

Will revert if the **next call** does not revert with the expected data `message`.

After calling `expectRevert`, calls to other cheatcodes before the reverting call are ignored.

This means, for example, another cheatcode such as `prank` may be called immediately before the reverting call.

#### 🖼️ Mockups/Examples

To use `expectRevert` with a `string`, pass it as a string literal.

```solidity
vm.expectRevert("error message");
```

To use `expectRevert` with a custom [error type][error-type] without parameters, use its selector.

```solidity
vm.expectRevert(CustomError.selector);
```

To use `expectRevert` with a custom [error type][error-type] with parameters, ABI encode the error type.

```solidity
vm.expectRevert(
    abi.encodeWithSelector(CustomError.selector, 1, 2)
);
```

If you need to assert that a function reverts _without_ a message, you can do so with `expectRevert(bytes(""))`.

```solidity
function testExpectRevertNoReason() public {
    Reverter reverter = new Reverter();
    vm.expectRevert(bytes(""));
    reverter.revertWithoutReason();
}
```

Message-less reverts happen when there is an EVM error, such as when the transaction consumes more than the block's gas limit.

If you need to assert that a function reverts a four character message, e.g. `AAAA`, you can do so with:

```solidity
function testFourLetterMessage() public {
    vm.expectRevert(bytes("AAAA"));
}
```

If used `expectRevert("AAAA")`, the compiler would throw an error because it wouldn't know which overload to use.

Finally, you can also have multiple `expectRevert()` checks in a single test.

```solidity
function testMultipleExpectReverts() public {
    vm.expectRevert("INVALID_AMOUNT");
    vault.send(user, 0);

    vm.expectRevert("INVALID_ADDRESS");
    vault.send(address(0), 200);
}
```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should have three implementations: (i) accepts no parameters (ii) accepts `bytes4` parameter (iii) accepts `bytes` parameter
    - It should revert if the following call does not revert with the expected message.

2. **Unit Tests:**
    - Write unit tests ensuring `expectRevert()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `expectRevert()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.expectRevert()`
- [ ] Write tests for `expectRevert()`
- [ ] Add inline documentation for `expectRevert()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
