### ISSUE TITLE
Implement `vm.readCallers()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#171]
#### 📝 Description

Implementing the `vm.readCallers()` [cheat code](https://book.getfoundry.sh/cheatcodes/read-callers).

**Declaration**
```solidity
enum CallerMode {
    None,
    Broadcast,
    RecurrentBroadcast,
    Prank,
    RecurrentPrank
}

function readCallers() 
external 
returns (CallerMode callerMode, address msgSender, address txOrigin);
```

#### 🤔 Rationale

This method is required to read the current `CallerMode`, `msg.sender`, and `tx.origin`.

The `CallerMode` enum indicates if there is an active caller modification and the type.

- If there is an active prank:
  - `callerMode` will be equal to:
    - `CallerMode.Prank` if the prank has been set with [`prank`](./prank.md).
    - `CallerMode.RecurrentPrank` if the prank has been set with [`startPrank`](./start-prank.md).

- If there is an active broadcast:
  - `callerMode` will be equal to:
    - `CallerMode.Broadcast` if the broadcast has been set with [`broadcast`](./broadcast.md).
    - `CallerMode.RecurrentBroadcast` if the broadcast has been set with [`startBroadcast`](./start-broadcast.md).

- If no caller modification is active:
  - `callerMode` will be equal to `CallerMode.None`.

#### 🖼️ Mockups/Examples

```solidity
CallerMode callerMode;
address msgSender;
address txOrigin;

// Example 1
(callerMode, msgSender, txOrigin) = vm.readCallers();
assertEq(callerMode, CallerMode.None);
assertEq(msgSender, defaultSenderAddress);
assertEq(txOrigin, defaultOriginAddress);

// Example 2
vm.prank(senderPrankAddress);
(callerMode, msgSender, txOrigin) = vm.readCallers();
assertEq(callerMode, CallerMode.Prank);
assertEq(msgSender, senderPrankAddress);
assertEq(txOrigin, defaultOriginAddress);

// Example 3
vm.prank(senderPrankAddress, originPrankAddress);
(callerMode, msgSender, txOrigin) = vm.readCallers();
assertEq(callerMode, CallerMode.Prank);
assertEq(msgSender, senderPrankAddress);
assertEq(txOrigin, originPrankAddress);

// Example 4
vm.broadcast(broadcastAddress);
(callerMode, msgSender, txOrigin) = vm.readCallers();
assertEq(callerMode, CallerMode.Broadcast);
assertEq(msgSender, broadcastAddress);
assertEq(txOrigin, broadcastAddress);
```

#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should take no parameters.
    - It should set return `(callerMode, msgSender, txOrigin)`.

2. **Unit Tests:**
    - Write unit tests ensuring `readCallers()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `readCallers()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.readCallers()`
- [ ] Write tests for `readCallers()`
- [ ] Add inline documentation for `readCallers()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
