### ISSUE TITLE
Implement `vm.toString()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#172]
#### 📝 Description

Implementing the `vm.toString()` [cheat code](https://book.getfoundry.sh/cheatcodes/to-string).

**Declaration**
```solidity
function toString(address) external returns (string memory);
function toString(bool) external returns (string memory);
function toString(uint256) external returns (string memory);
function toString(int256) external returns (string memory);
function toString(bytes32) external returns (string memory);
function toString(bytes) external returns (string memory);
```

#### 🤔 Rationale

This method is required to convert any type to its string version. Very useful for operations that demand strings, such as the cheatcode `ffi` (invariant testing).

Bytes are converted to a string of their hex representation with 0x at the start, signifying that they are encoded in hex.

#### 🖼️ Mockups/Examples

```solidity
uint256 number = 420;
string memory stringNumber = vm.toString(number);
vm.assertEq(stringNumber, "420");
```

```solidity
bytes memory testBytes = hex"7109709ECfa91a80626fF3989D68f67F5b1DD12D";
string memory stringBytes = cheats.toString(testBytes);
assertEq("0x7109709ecfa91a80626ff3989d68f67f5b1dd12d", stringBytes);
```

```solidity
address testAddress =  0x7109709ECfa91a80626fF3989D68f67F5b1DD12D;
string memory stringAddress = cheats.toString(testAddress);
assertEq("0x7109709ECfa91a80626fF3989D68f67F5b1DD12D", stringAddress);
```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should accept parameters of types `address`, `bool`, `uint256`, `int256`, `bytes32` and `bytes`.
    - It should set return the string representation of the provided value.

2. **Unit Tests:**
    - Write unit tests ensuring `toString()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `toString()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.toString()`
- [ ] Write tests for `toString()`
- [ ] Add inline documentation for `toString()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
