### ISSUE TITLE
Implement `vm.addr()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#173]
#### 📝 Description

Implementing the `vm.addr()` [cheat code](https://book.getfoundry.sh/cheatcodes/addr).

**Declaration**
```solidity
function addr(uint256 privateKey) external returns (address);
```

#### 🤔 Rationale

This method is required to compute the address for a given private key.

#### 🖼️ Mockups/Examples

```solidity
address alice = vm.addr(1);
emit log_address(alice); // 0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
```

```solidity
  function e2eTestAsset(
    ILendingPool pool,
    ReserveConfig memory collateralConfig,
    ReserveConfig memory testAssetConfig
  ) public {
    console.log(
      'E2E: Collateral %s, TestAsset %s',
      collateralConfig.symbol,
      testAssetConfig.symbol
    );
    address collateralSupplier = vm.addr(3);
    address testAssetSupplier = vm.addr(4);
    ...
 ```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should accept a `uint256` private key value.
    - It should set return the `address` for the provided private key value.

2. **Unit Tests:**
    - Write unit tests ensuring `addr()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `addr()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.addr()`
- [ ] Write tests for `addr()`
- [ ] Add inline documentation for `addr()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
