### ISSUE TITLE
Implement `vm.stopPrank()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#174]
#### 📝 Description

Implementing the `vm.stopPrank()` [cheat code](https://book.getfoundry.sh/cheatcodes/stop-prank).

**Declaration**
```solidity
function stopPrank() external;
```

#### 🤔 Rationale

This method is required to stop an active prank started by [`startPrank`](https://book.getfoundry.sh/cheatcodes/start-prank.html), resetting `msg.sender` and `tx.origin` to the values before `startPrank` was called.

#### 🖼️ Mockups/Examples

```solidity
  /**
   * @dev Impersonate the ecosystem reserve and creates the proposal.
   */
  function createTestProposal(
    Vm vm,
    Payload[] memory payloads,
    address executor
  ) internal returns (uint256) {
    vm.deal(MiscEthereum.ECOSYSTEM_RESERVE, 1 ether);
    vm.startPrank(MiscEthereum.ECOSYSTEM_RESERVE);
    uint256 proposalId = _createProposal(executor, payloads, bytes32('test'), false);
    vm.stopPrank();
    return proposalId;
  }
```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should have no parameters.
    - It should revert the execution environment `msg.sender` and `tx.origin` to values set before `prank` was initiated.

2. **Unit Tests:**
    - Write unit tests ensuring `stopPrank()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `stopPrank()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.stopPrank()`
- [ ] Write tests for `stopPrank()`
- [ ] Add inline documentation for `stopPrank()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
