### ISSUE TITLE
Implement `vm.startPrank()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#175]
#### 📝 Description

Implementing the `vm.startPrank()` [cheat code](https://book.getfoundry.sh/cheatcodes/start-prank).

**Declaration**
```solidity
function startPrank(address) external; // main declaration
function startPrank(address sender, address origin) external; // alternative declaration
```

#### 🤔 Rationale

This method is required to set `msg.sender` for all subsequent calls until [stopPrank](https://book.getfoundry.sh/cheatcodes/stop-prank.html) is called.

If the alternative signature is used, then `tx.origin` is set as well for all subsequent calls.

#### 🖼️ Mockups/Examples

```solidity
  /**
   * @dev Impersonate the ecosystem reserve and creates the proposal.
   */
  function createTestProposal(
    Vm vm,
    Payload[] memory payloads,
    address executor
  ) internal returns (uint256) {
    vm.deal(MiscEthereum.ECOSYSTEM_RESERVE, 1 ether);
    vm.startPrank(MiscEthereum.ECOSYSTEM_RESERVE);
    uint256 proposalId = _createProposal(executor, payloads, bytes32('test'), false);
    vm.stopPrank();
    return proposalId;
  }
  ```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should accept an `address` value.
    - Alternative implementation should accept two `address` parameters.
    - Main implementation should set the execution environment `who` address' contract to the bytes passed as an argument.
    - Alternative implementation should additionally set `tx.origin` value to provided value for subsequent calls.

2. **Unit Tests:**
    - Write unit tests ensuring `startPrank()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `startPrank()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.startPrank()`
- [ ] Write tests for `startPrank()`
- [ ] Add inline documentation for `startPrank()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
