### ISSUE TITLE
Implement `vm.etch()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#176]
#### 📝 Description

Implementing the `vm.etch()` [cheat code](https://book.getfoundry.sh/cheatcodes/etch).

**Declaration**
```solidity
function etch(address who, bytes calldata code) external;
```

#### 🤔 Rationale

This method is required to set the bytecode of an address `who` to `code`.

#### 🖼️ Mockups/Examples

```solidity
  /**
   * @dev executes specified payloadAddress on a specified executor via delegatecall
   * @notice this method accepts arbitrary executors (guardians and executors)
   * @param vm Vm instance passed down from test
   * @param executor address of the executor
   * @param payloadAddress address of payload to execute
   */
  function executePayload(Vm vm, address payloadAddress, address executor) internal {
    if (
      block.chainid == ChainIds.MAINNET &&
      (executor == AaveGovernanceV2.SHORT_EXECUTOR || executor == AaveGovernanceV2.LONG_EXECUTOR)
    ) {
      Payload[] memory proposals = new Payload[](1);
      proposals[0] = Payload({
        target: payloadAddress,
        signature: 'execute()',
        callData: '',
        withDelegatecall: true,
        value: 0
      });
      uint256 proposalId = _queueProposalToL1ExecutorStorage(vm, executor, proposals);
      AaveGovernanceV2.GOV.execute(proposalId);
    } else if (_isKnownL2Executor(executor)) {
      Payload[] memory proposals = new Payload[](1);
      proposals[0] = Payload({
        target: payloadAddress,
        signature: 'execute()',
        callData: '',
        withDelegatecall: true,
        value: 0
      });
      uint256 proposalId = _queueProposalToL2ExecutorStorage(vm, executor, proposals);
      CommonExecutor(executor).execute(proposalId);
    } else {
      MockExecutor mockExecutor = new MockExecutor();
      vm.etch(executor, address(mockExecutor).code); // <<------ set bytecode 
      MockExecutor(executor).execute(payloadAddress);
    }
  }
  ```

```solidity
bytes memory code = address(awesomeContract).code;
address targetAddr = makeAddr("target");
vm.etch(targetAddr, code);
log_bytes(address(targetAddr).code); // 0x6080604052348015610010...
```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should accept an `address` and `bytes` values.
    - It should set the execution environment `who` address' contract to the bytes passed as an argument.

2. **Unit Tests:**
    - Write unit tests ensuring `etch()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `etch()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.etch()`
- [ ] Write tests for `etch()`
- [ ] Add inline documentation for `etch()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
