### ISSUE TITLE
Implement `vm.roll()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#177]
#### 📝 Description

Implementing the `vm.roll()` [cheat code](https://book.getfoundry.sh/cheatcodes/roll).

#### 🤔 Rationale

This method is required to set block numbers for tests.

#### 🖼️ Mockups/Examples

```solidity
  /**
   * Alter storage slots so the proposal passes
   */
  function passVote(Vm vm, uint256 proposalId) internal {
    uint256 power = 5000000 ether;
    vm.roll(block.number + 1);
    vm.store(
      address(AaveGovernanceV2.GOV),
      bytes32(uint256(keccak256(abi.encode(proposalId, 0x4))) + 11),
      bytes32(power)
    );
    uint256 endBlock = AaveGovernanceV2.GOV.getProposalById(proposalId).endBlock;
    vm.roll(endBlock + 1);
  }
```

```solidity
vm.roll(100);
emit log_uint(block.number); // 100
```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should accept a `uint256` value.
    - It should set the execution environment block number to that value.

2. **Unit Tests:**
    - Write unit tests ensuring `vm.roll()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `roll()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.roll()`
- [ ] Write tests for `roll()`
- [ ] Add inline documentation for `roll()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
