### ISSUE TITLE
Implement `vm.deal()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#178]
#### 📝 Description

Implementing the `vm.deal()` [cheat code](https://book.getfoundry.sh/cheatcodes/deal).

**Declaration**
```solidity
function deal(address who, uint256 newBalance) external;
```

#### 🤔 Rationale

This method is required to set the balance of an address `who` to `newBalance`.

Also provide an alternative signature of deal (defined in a separate module e.g. StdCheats.sol), to additionally specify ERC20 token address, as well as an option to update totalSupply.

#### 🖼️ Mockups/Examples

```solidity
address alice = makeAddr("alice");
emit log_address(alice);
deal(address(DAI), alice, 1 ether); // import StdUtils.sol first
log_uint256(address(DAI).balanceOf(alice)); // 1000000000000000000
  ```

```solidity
address alice = makeAddr("alice");
emit log_address(alice);
vm.deal(alice, 1 ether);
log_uint256(alice.balance); // 1000000000000000000
```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should accept an `address` and a `uint256` value.
    - It should set the balance of the provided address to the provided new balance.

2. **Unit Tests:**
    - Write unit tests ensuring `vm.deal()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `deal()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.deal()`
- [ ] Write tests for `vm.deal()`
- [ ] Add inline documentation for `vm.deal()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
