### ISSUE TITLE
Implement `vm.warp()`

### ISSUE THREAD

**Issue by idea404** [matter-labs/foundry-zksync#179]
#### 📝 Description

Implementing the `vm.warp()` [cheat code](https://book.getfoundry.sh/cheatcodes/warp).

#### 🤔 Rationale

This method is required to set block timestamps for tests.

#### 🖼️ Mockups/Examples

```solidity
  function passVoteAndExecute(Vm vm, uint256 proposalId) internal {
    passVoteAndQueue(vm, proposalId);
    uint256 executionTime = AaveGovernanceV2.GOV.getProposalById(proposalId).executionTime;
    vm.warp(executionTime + 1);
    AaveGovernanceV2.GOV.execute(proposalId);
  }
  ```

```solidity
vm.warp(1641070800);
emit log_uint(block.timestamp); // 1641070800
```
  
#### 🖋️Requirements 

1. **Implement the Method:**
    - The method should accept a `uint256` value.
    - It should set the execution environment block timestamp to that value.

2. **Unit Tests:**
    - Write unit tests ensuring `vm.warp()` functions correctly.
    - Test with different input values, including invalid ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `warp()` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

#### 🎯Task Checklist

- [ ] Implement `vm.warp()`
- [ ] Write tests for `vm.warp()`
- [ ] Add inline documentation for `vm.warp()` 

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
