### ISSUE TITLE
[CHECKLIST] Achieve Full forge command parity with upstream for ZKsync

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/foundry-zksync#622]
## Description 

This issue tracks progress on achieving full command parity between `forge` on `foundry-zksync` and upstream `foundry`. Implementing these features will ensure a smooth developer experience and complete compatibility with ZKsync.

### Task Checklist

- [ ] https://github.com/matter-labs/foundry-zksync/issues/619
- [ ] https://github.com/matter-labs/foundry-zksync/issues/615
- [ ] https://github.com/matter-labs/foundry-zksync/issues/475
- [ ] https://github.com/matter-labs/foundry-zksync/issues/576
- [ ] https://github.com/matter-labs/foundry-zksync/issues/621
