### ISSUE TITLE
[CHECKLIST] Achieve Full cast command parity

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/foundry-zksync#630]
## Description 

This issue tracks progress on achieving full command parity between `cast` on foundry-zksync and upstream foundry. Implementing these features will provide a smooth developer experience and complete compatibility with ZKsync.

### Task Checklist 

- [ ] https://github.com/matter-labs/foundry-zksync/issues/616
- [ ] https://github.com/matter-labs/foundry-zksync/issues/617
- [ ] https://github.com/matter-labs/foundry-zksync/issues/618
- [ ] https://github.com/matter-labs/foundry-zksync/issues/620
- [ ] https://github.com/matter-labs/foundry-zksync/issues/623
- [ ] https://github.com/matter-labs/foundry-zksync/issues/624
- [ ] https://github.com/matter-labs/foundry-zksync/issues/625
- [ ] https://github.com/matter-labs/foundry-zksync/issues/626
- [ ] https://github.com/matter-labs/foundry-zksync/issues/627
- [ ] https://github.com/matter-labs/foundry-zksync/issues/628
- [ ] https://github.com/matter-labs/foundry-zksync/issues/629
